version: "3.9"
services:
  db:
    image: postgres:latest
    container_name: database
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - network
    ports:
      - 54320:5432
    volumes:
      - db_data:/var/lib/postgresql/data
networks:
  network:
    driver: bridge

volumes:
  db_data:
